### ISSUE TITLE
Input PE image does not contain a .NET metadata directory

### ISSUE THREAD

**Issue by darkSuperman** [sunnamed434/BitMono#136]
Hello, thank you for your contribution to this very meaningful project.
I had a problem after using it. I checked the issue list and found no similar problem to mine. The following is the error log. There are a few Chinese characters in it. Please don’t worry about it.（My application is written on .net 5, and I choose not to rely on the external environment and simplify unused code when publishing）

```
][BitMono.CLI.Modules.CLIObfuscationNeedsFactory] File successfully specified: *
**\Demo.exe
[2023-07-25 09:08:48 INF][BitMono.CLI.Modules.CLIObfuscationNeedsFactory] Depend
encies (libs) directory was automatically found in: ***\libs!
[2023-07-25 09:08:48 INF][BitMono.CLI.Program] File: ***\Demo.exe
[2023-07-25 09:08:48 INF][BitMono.CLI.Program] Dependencies (libs): ***\libs
[2023-07-25 09:08:48 INF][BitMono.CLI.Program] Everything is seems to be ok, sta
rting obfuscation..
[2023-07-25 09:08:48 INF][BitMono.CLI.Program]
       ___  _ __  __  ___
      / _ )(_) /_/  |/  /__  ___  ___
     / _  / / __/ /|_/ / _ \/ _ \/ _ \
    /____/_/\__/_/  /_/\___/_//_/\___/
    https://github.com/sunnamed434/BitMono
    BitMono v0.16.2.0
Something went wrong! System.BadImageFormatException: Input PE image does not contain a .NET metadata directory.
   在 AsmResolver.DotNet.Serialized.SerializedModuleDefinition..ctor(IPEImage pe
Image, ModuleReaderParameters readerParameters)
   在 AsmResolver.DotNet.ModuleDefinition.FromBytes(Byte[] buffer, ModuleReaderP
arameters readerParameters)
   在 BitMono.Obfuscation.Modules.ModuleFactory.Create()
   在 BitMono.Obfuscation.Starter.BitMonoStarter.StartAsync(FinalFileInfo info,
IModuleFactory moduleFactory, IDataWriter dataWriter, IReferencesDataResolver re
ferencesDataResolver, CancellationToken cancellationToken)
   在 BitMono.Obfuscation.Starter.BitMonoStarter.StartAsync(IncompleteFileInfo i
nfo, CancellationToken cancellationToken)
   在 BitMono.CLI.Program.<Main>d__3.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 BitMono.CLI.Program.<Main>d__3.MoveNext()
Enter anything to exit!
```

**Comment by sunnamed434** [comment]
Hey!

Thanks! Me and contributors doing our best!

As far as I know, .NET 5 compiling into the native code, but the .NET 5 application should have a `.dll` file with all of your managed code inside. That means in the root folder of the `Demo.exe` should be a `Demo.dll` - which contains the managed code, and you need to protect this instead of `Demo.exe`

**Comment by sunnamed434** [comment]
I think yes its related to the 'self-contained' publish option, try to publish it with non self contained option and the dll should appear or try to uncheck the single file option

**Comment by sunnamed434** [comment]
Hey, can you please send the `Demo.dll` to my email: `sunnamed434@proton.me`

**Comment by sunnamed434** [comment]
I guess the problem is more that the BitMono TargetFramework is .NET Framework 461, it would be great to add support for the .NET 5/6, etc

**Comment by sunnamed434** [comment]
Will check tommorow

**Comment by sunnamed434** [comment]
You can ignore those exceptions, the problem can be caused due to BitMono using .NET Framework. I specified a few protections and the file is obfuscated successfully that you provided in my email, to make it work simply configure `protections.json`

The solution is to add a .NET 6/5 to the bitmono target frameworks

**Comment by sunnamed434** [comment]
`Name` is the name of the protection
`Enabled` is a state of protection (enabled or not)

Here's my best preset for obfuscation, but, since your app forms don't use my preset because it works only on Mono runtime, and this your application won't run without specific runtime (i.e Mono)

```json
{
  "Protections": [
    {
      "Name": "AntiILdasm",
      "Enabled": false
    },
    {
      "Name": "AntiDe4dot",
      "Enabled": false
    },
    {
      "Name": "ObjectReturnType",
      "Enabled": false
    },
    {
      "Name": "NoNamespaces",
      "Enabled": false
    },
    {
      "Name": "FullRenamer",
      "Enabled": false
    },
    {
      "Name": "AntiDebugBreakpoints",
      "Enabled": false
    },
    {
      "Name": "StringsEncryption",
      "Enabled": false
    },
    {
      "Name": "UnmanagedString",
      "Enabled": false
    },
    {
      "Name": "DotNetHook",
      "Enabled": false
    },
    {
      "Name": "CallToCalli",
      "Enabled": false
    },
    {
      "Name": "AntiDecompiler",
      "Enabled": true
    },
    {
      "Name": "BitMethodDotnet",
      "Enabled": true
    },
    {
      "Name": "BitTimeDateStamp",
      "Enabled": true
    },
    {
      "Name": "BitDotNet",
      "Enabled": true
    },
    {
      "Name": "BitMono",
      "Enabled": true
    }
  ]
}
```

I recommend using this preset for you: `DotNetHook` , `CallToCalli`, `BitTimeDateStamp`, and `UnmanagedString`

**Comment by sunnamed434** [comment]
Here: `Release\net462\protections.json`

**Comment by sunnamed434** [comment]
For now yes, I'll create another issue
